name: waterreminder
description: Water reminder App.
publish_to: 'none'
version: 1.0.4+5

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animations: ^2.0.0
  flutter_bloc: ^7.0.0
  rxdart: ^0.26.0
  shared_preferences: ^2.0.15
  flutter_local_notifications: ^17.0.0
  permission_handler: ^11.0.1
  android_alarm_manager_plus: ^5.0.0
  timezone: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
  


